---
title: "Sergio Fajardo Valderrama"
page-layout: article
---

```{r}
project_dir <- normalizePath('..', winslash = '/', mustWork = TRUE)
source(file.path(project_dir, 'R', 'site_helpers.R'))
candidate_key <- 'sergio-fajardo'
candidate_slug <- 'sergio-fajardo'
candidate_name <- 'Sergio Fajardo Valderrama'
candidate_meta <- read_candidate_registry_public(project_dir) |> dplyr::filter(.data$candidate_id == candidate_key)
taxonomy <- read_taxonomy_public(project_dir)
dossiers <- read_processed_table('candidate_dossiers.csv', project_dir = project_dir)
claims <- read_processed_table('claim_records.csv', project_dir = project_dir)
analysis_notes <- read_processed_table('analysis_notes.csv', project_dir = project_dir)
sources <- read_processed_table('source_records.csv', project_dir = project_dir)
candidate_dossier <- dossiers |> dplyr::filter(.data$candidate_id == candidate_key)
candidate_claims <- claims |> dplyr::filter(.data$candidate_id == candidate_key) |> dplyr::arrange(dplyr::desc(.data$event_date))
candidate_analysis <- analysis_notes |> dplyr::filter(.data$candidate_id == candidate_key)
candidate_sources <- sources |> dplyr::filter(.data$candidate_id == candidate_key) |> dplyr::arrange(dplyr::desc(.data$published_at))
```

## Ficha base

```{r}
#| results: asis
emit_candidate_header(candidate_meta, candidate_dossier)
```

## Ubicación ideológica

```{r}
#| results: asis
emit_candidate_ideology(candidate_dossier)
```

## Trayectoria y contexto público

```{r}
#| results: asis
emit_candidate_background(candidate_claims, candidate_sources)
```

## Propuestas y posiciones públicas

```{r}
#| results: asis
emit_candidate_policy_sections(candidate_claims, candidate_sources, taxonomy)
```

## Análisis lógico publicado

```{r}
#| results: asis
emit_candidate_analysis(candidate_analysis, candidate_sources)
```

## Biblioteca de fuentes

```{r}
#| results: asis
emit_candidate_source_library(candidate_sources)
```
